service: workshop-snssqs
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless
  region: eu-west-1
  apiGateway:
    apiKeys:
      - order-function-key
  environment:
    ACCOUNT_ID: ${aws:accountId}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'sns:Publish'
          Resource:
            - '*'

functions:
  OrderFunction:
    handler: order-function/handler.handle
    events:
      - http:
          path: /
          method: post
          private: true


plugins:
  - serverless-esbuild

resources:
  Resources:

    ## Order Function

    OrderCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: order-created-event
